# Copyright (c) 2026 Everypin
# GNU General Public License v3.0 (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

from importlib.metadata import PackageNotFoundError, version

from jig.common.config import JigConfig
from jig.common.stand_cloud import StandCloudConnector, StandCloudError
from jig.pytest_jig.db import (
    Chart,
    Instrument,
    NumericMeasurement,
    StringMeasurement,
    SubUnit,
)
from jig.pytest_jig.pytest_call import (
    ErrorCode,
    PassFailDialog,
    clear_operator_message,
    get_current_attempt,
    get_current_report,
    get_jig_config,
    run_dialog_box,
    set_batch_serial_number,
    set_case_artifact,
    set_case_chart,
    set_case_measurement,
    set_driver_info,
    set_dut_info,
    set_dut_name,
    set_dut_part_number,
    set_dut_revision,
    set_dut_serial_number,
    set_dut_sub_unit,
    set_dut_type,
    set_instrument,
    set_message,
    set_module_artifact,
    set_operator_message,
    set_process_info,
    set_process_name,
    set_process_number,
    set_run_artifact,
    set_stand_info,
    set_stand_location,
    set_stand_name,
    set_stand_number,
    set_stand_revision,
    set_user_name,
)
from jig.pytest_jig.result import (
    CouchdbLoader,
    JsonLoader,
    StandCloudLoader,
    StandCloudReader,
)
from jig.pytest_jig.result.couchdb_config import CouchdbConfig
from jig.pytest_jig.utils import (
    BaseWidget,
    ChartType,
    CheckboxWidget,
    ComparisonOperation,
    DialogBox,
    DuplicateParameterError,
    Group,
    HTMLComponent,
    ImageComponent,
    MultistepWidget,
    NumericInputWidget,
    RadiobuttonWidget,
    StepWidget,
    TestStandNumberError,
    TextInputWidget,
)

#: PyPI distribution name, which differs from the `jig` import name.
DISTRIBUTION_NAME = "pytest-jig"

try:
    __version__ = version(DISTRIBUTION_NAME)
except PackageNotFoundError:
    __version__ = "unknown"

__all__ = [
    "BaseWidget",
    "Chart",
    "ChartType",
    "CheckboxWidget",
    "ComparisonOperation",
    "CouchdbConfig",
    "CouchdbLoader",
    "DialogBox",
    "DuplicateParameterError",
    "ErrorCode",
    "Group",
    "HTMLComponent",
    "ImageComponent",
    "Instrument",
    "JigConfig",
    "JsonLoader",
    "MultistepWidget",
    "NumericInputWidget",
    "NumericMeasurement",
    "PassFailDialog",
    "RadiobuttonWidget",
    "StandCloudConnector",
    "StandCloudError",
    "StandCloudLoader",
    "StandCloudReader",
    "StepWidget",
    "StringMeasurement",
    "SubUnit",
    "TestStandNumberError",
    "TextInputWidget",
    "clear_operator_message",
    "get_current_attempt",
    "get_current_report",
    "get_jig_config",
    "run_dialog_box",
    "set_batch_serial_number",
    "set_case_artifact",
    "set_case_chart",
    "set_case_measurement",
    "set_driver_info",
    "set_dut_info",
    "set_dut_name",
    "set_dut_part_number",
    "set_dut_revision",
    "set_dut_serial_number",
    "set_dut_sub_unit",
    "set_dut_type",
    "set_instrument",
    "set_message",
    "set_module_artifact",
    "set_operator_message",
    "set_process_info",
    "set_process_name",
    "set_process_number",
    "set_run_artifact",
    "set_stand_info",
    "set_stand_location",
    "set_stand_name",
    "set_stand_number",
    "set_stand_revision",
    "set_user_name",
]
